# Generated by Django 5.1.7 on 2025-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0008_remove_attendance_unique_staff_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_date'),
        ),
    ]
