# Generated by Django 5.1.7 on 2025-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0009_attendance_unique_staff_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Tokyo Business International', max_length=100)),
                ('working_hours', models.CharField(default='9:00 - 17:00', max_length=50)),
                ('currency', models.CharField(default='Yen-¥', max_length=10)),
                ('overtime_rate', models.FloatField(default=1.5)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
