# Generated by Django 5.1.7 on 2025-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0011_remove_staff_role_staff_groups_staff_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='staff_cvs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='b', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='ab', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
