# Generated by Django 5.0.6 on 2025-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0012_staff_cv_staff_dob_staff_first_name_staff_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='certificate_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='certificate_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('Experience', 'Experience'), ('Training', 'Training'), ('Achievement', 'Achievement')], max_length=50, null=True),
        ),
    ]
