# Generated by Django 5.0.6 on 2025-03-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0013_staff_certificate_description_staff_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
